build:
    environment:
        php:
            version: 7.0.8
    dependencies:
        override:
            - find . -delete
            - git clone https://github.com/octobercms/october.git .
            - composer install --no-interaction --prefer-source
            - mkdir -p ./plugins/tohur/bookings
            - cd plugins/tohur/bookings && git clone https://github.com/tohur/oc-bookings-plugin.git .
            - composer install
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage'
                coverage:
                    file: './plugins/tohur/bookings/coverage'
                    format: 'php-clover'
checks:
    php:
        code_rating: true
        duplication: true
