language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - git clone https://github.com/octobercms/october.git
  - mkdir -p ./october/plugins/tohur/bookings
  - mv !(october) october/plugins/tohur/bookings
  - cd october
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - cd plugins/tohur/bookings
  - composer install
  - npm install

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
  - npm test
