plugin:
    name: 'tohur.bookings::lang.plugin.name'
    description: 'tohur.bookings::lang.plugin.description'
    author: 'Vojta Svoboda'
    icon: icon-calendar-o
permissions:
    tohur.bookings.bookings:
        tab: tohur.bookings::lang.permission.tab_label
        label: tohur.bookings::lang.permission.bookings
    tohur.bookings.statuses:
        tab: tohur.bookings::lang.permission.tab_label
        label: tohur.bookings::lang.permission.statuses
    tohur.bookings.export:
        tab: tohur.bookings::lang.permission.tab_label
        label: tohur.bookings::lang.permission.export
