name: Booking
modelClass: Tohur\Bookings\Models\Booking
form: $/tohur/bookings/models/booking/fields.yaml
defaultRedirect: tohur/bookings/bookings
create:
    redirect: 'tohur/bookings/bookings/update/:id'
    redirectClose: tohur/bookings/bookings
update:
    redirect: tohur/bookings/bookings
    redirectClose: tohur/bookings/bookings
preview: {  }
