export:
    title: Export
    modelClass: Tohur\Bookings\Models\BookingExport
    list: $/tohur/bookings/models/bookingsexport/columns.yaml
    form: $/tohur/bookings/models/bookingsexport/fields.yaml
