title: Booking
modelClass: Tohur\Bookings\Models\Booking
list: $/tohur/bookings/models/booking/columns.yaml
filter: config_filter.yaml
recordUrl: 'tohur/bookings/bookings/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 200
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: id
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
