name: Statuses
modelClass: Tohur\Bookings\Models\Status
form: $/tohur/bookings/models/status/fields.yaml
defaultRedirect: tohur/bookings/statuses
create:
    redirect: 'tohur/bookings/statuses/update/:id'
    redirectClose: tohur/bookings/statuses
update:
    redirect: tohur/bookings/statuses
    redirectClose: tohur/bookings/statuses
preview: {  }
