title: Statuses
modelClass: Tohur\Bookings\Models\Status
list: $/tohur/bookings/models/status/columns.yaml
recordUrl: 'tohur/bookings/statuses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
